### ISSUE TITLE
WORKON

### ISSUE THREAD

**Issue by GerBreOwn** [cs-cordero/pyvenvwrapper#1]
Greetings:
The original "pyvenvwrapper" had a "WORKON" command that automatically CD to the project directory and activate the project.
Would it be possible to include this in your version of pyvenvwrapper?
Thanks,
Gerald S. Brown

**Comment by cs-cordero** [comment]
Thanks for the request!  I have made a commit updating the script which allows for `workon` and `mkproj` capability.  See the updated README.md for instructions and please let me know if you have any issues with it.

https://github.com/cs-cordero/pyvenvwrapper/commit/eb058ab5d51e4ca5b4701b988498572022533260
