### ISSUE TITLE
rmvenv() destructive

### ISSUE THREAD

**Issue by averms** [cs-cordero/pyvenvwrapper#3]
I don't use this anymore but I noticed that if you run `rmvenv` without any arguments it will destroy `$VENV_HOME`. Should probably check for the instance of 0 args being passed in.

**Comment by averms** [comment]
Here's a possible solution from my fork:

https://github.com/a-vrma/vewrapper/blob/36b2ba19f459b517c21e7f6f751f2b0ef06bf42a/vewrapper.bash#L57-L69

**Comment by cs-cordero** [comment]
Thanks @a-vrma !  Apologies for not being super responsive on this project.  For a while I started using `pipenv` but I'm coming back to this as my preferred environment handler.

This overly destructive behavior is now handled in 

https://github.com/cs-cordero/pyvenvwrapper/commit/fe6b44b1cfd36d8262bab8cac4e3b899471ce24a
